# dataset parameters
WINDOW_SIZE = 5
MIN_WORD_FREQUENCY = 5
NEGATIVE_SAMPLES = 5

# training parameters
EPOCHS = 13
LEARNING_RATE = 0.001
EMBEDDING_DIM = 100
BATCH_SIZE = 512
EPSILON = 1e-10

# checkpointing
MAKE_CHECKPOINTS = True
CHECKPOINT_INTERVAL = 2 # should be > 0
CHECKPOINT_NAME = "sgns_save.npz"